"""Build example notebooks as JSON files.

Usage: python examples/_build_notebooks.py

Keeps notebook content in one place, makes review easier than editing JSON directly.
Run from repo root.
"""

import json
from pathlib import Path


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["\n".join(lines)],
    }


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": ["\n".join(lines)],
    }


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def step_zero_cells() -> list[dict]:
    """Reusable Step 0: optional dev-install from source + environment check."""
    return [
        md(
            "## Step 0: Dev setup, environment check & credentials",
            "",
            "This cell does three things:",
            "",
            "1. **Dev toggle** — set `USE_LOCAL_SRC = True` to import the library directly from this repo's `src/` tree instead of a pip-installed version. Useful for developers testing changes, or for trying the library without installing it. Regular users leave it `False`.",
            "2. **Environment check** — verifies Python >= 3.11 and all required dependencies, so you get a clear error up front instead of a confusing failure mid-notebook.",
            "3. **Credentials helpers** — defines two functions you can call in Step 1:",
            "    - `show_credentials_form()` — renders an ipywidgets form (username + password field + Submit button) right in the notebook. Best for interactive use.",
            "    - `get_credentials()` — blocking text-prompt fallback. Best for automation / scripted notebooks.",
            "    Both first check `FFIEC_USERNAME` / `FFIEC_BEARER_TOKEN` env vars and a `.env` file, and skip the UI if those already supply both values.",
            "",
            "**Three ways to supply credentials** (Step 0 picks whichever is available):",
            "",
            "- **Env vars** — `export FFIEC_USERNAME=... FFIEC_BEARER_TOKEN=ey...` before launching Jupyter.",
            "- **`.env` file** — create `.env` in the notebook's directory with the same two variables. Requires `pip install python-dotenv`. Remember to `.gitignore` it.",
            "- **Interactive form** — leave both unset and `show_credentials_form()` (in Step 1) will render a widget with a hidden password field. Requires `pip install ipywidgets` (falls back to a text prompt otherwise).",
        ),
        code(
            "import os",
            "import sys",
            "import warnings",
            "from pathlib import Path",
            "",
            "# Flip to True to load ffiec_data_connect from the local repo src/ tree (dev mode).",
            "USE_LOCAL_SRC = False",
            "",
            "if USE_LOCAL_SRC:",
            "    # Walk upward from the notebook's CWD to find a sibling `src/ffiec_data_connect`.",
            "    here = Path.cwd().resolve()",
            "    src_root = None",
            "    for candidate in [here, *here.parents]:",
            "        if (candidate / 'src' / 'ffiec_data_connect' / '__init__.py').exists():",
            "            src_root = candidate / 'src'",
            "            break",
            "    if src_root is None:",
            "        raise RuntimeError(",
            "            'USE_LOCAL_SRC=True but no src/ffiec_data_connect found '",
            "            'walking up from ' + str(here)",
            "        )",
            "    sys.path.insert(0, str(src_root))",
            "    # Evict any previously-imported copy so the src/ tree wins on next import.",
            "    for mod_name in [m for m in sys.modules if m == 'ffiec_data_connect' or m.startswith('ffiec_data_connect.')]:",
            "        del sys.modules[mod_name]",
            "    print(f'Loading ffiec_data_connect from: {src_root}')",
            "",
            "# --- Environment support check -------------------------------------------",
            "if sys.version_info < (3, 11):",
            "    raise RuntimeError(",
            "        f'ffiec-data-connect requires Python >= 3.11, got {sys.version.split()[0]}'",
            "    )",
            "",
            "REQUIRED = ['httpx', 'pandas', 'numpy', 'lxml', 'xmltodict', 'defusedxml', 'pydantic']",
            "missing = []",
            "for mod in REQUIRED:",
            "    try:",
            "        __import__(mod)",
            "    except ImportError:",
            "        missing.append(mod)",
            "if missing:",
            "    raise RuntimeError(",
            "        'Missing required dependencies: ' + ', '.join(missing) +",
            "        '\\nInstall with: pip install ffiec-data-connect'",
            "    )",
            "",
            "# Optional deps used by some notebooks — warn but don't fail here.",
            "OPTIONAL = {",
            "    'matplotlib': 'plotting cells (notebooks 02)',",
            "    'polars': 'polars output_type (optional extra: pip install ffiec-data-connect[polars])',",
            "    'pyarrow': 'parquet I/O (pip install pyarrow)',",
            "    'ipywidgets': 'interactive credentials form via show_credentials_form() (pip install ipywidgets)',",
            "    'dotenv': '.env file support for credentials (pip install python-dotenv)',",
            "}",
            "for mod, purpose in OPTIONAL.items():",
            "    try:",
            "        __import__(mod)",
            "    except ImportError:",
            "        warnings.warn(f'Optional dep {mod!r} not installed — needed for {purpose}', stacklevel=1)",
            "",
            "import ffiec_data_connect",
            "from ffiec_data_connect import OAuth2Credentials",
            "print(f'Python:              {sys.version.split()[0]}')",
            "print(f'ffiec_data_connect:  {ffiec_data_connect.__version__}')",
            "print(f'Loaded from:         {Path(ffiec_data_connect.__file__).parent}')",
            "print('Environment OK.')",
            "",
            "# --- Credentials helpers -------------------------------------------------",
            "# Two ways to authenticate:",
            "#   get_credentials()       — blocking. Tries env vars, then .env, then falls back to text prompts (input/getpass). Best for automation / scripts.",
            "#   show_credentials_form() — renders an ipywidgets form (username field + password field + Submit button). Best for interactive notebook use. Sets `creds` in the notebook's namespace when you click Submit.",
            "",
            "def _resolve_env_credentials():",
            "    \"\"\"Return (username, token) from env vars / .env, else (None|str, None|str).\"\"\"",
            "    username = os.environ.get('FFIEC_USERNAME')",
            "    token = os.environ.get('FFIEC_BEARER_TOKEN')",
            "    if not (username and token):",
            "        try:",
            "            from dotenv import load_dotenv",
            "            load_dotenv()",
            "            username = username or os.environ.get('FFIEC_USERNAME')",
            "            token = token or os.environ.get('FFIEC_BEARER_TOKEN')",
            "        except ImportError:",
            "            pass",
            "    return username, token",
            "",
            "def _warn_about_token_shape(token: str) -> None:",
            "    \"\"\"Soft-warn about common token-paste mistakes before OAuth2Credentials raises hard.",
            "",
            "    FFIEC-issued JWT bearer tokens have an idiosyncratic shape: they start with 'ey' and",
            "    **end with a literal '.'** (an empty third segment). Browsers and copy-paste sometimes",
            "    strip the trailing '.', which silently breaks auth. We warn early so a user can re-copy",
            "    rather than hitting a validation exception deeper in the call.",
            "    \"\"\"",
            "    if not token:",
            "        return",
            "    t = token.strip()",
            "    if not t.endswith('.'):",
            "        warnings.warn(",
            "            'Bearer token does not end with a \".\". FFIEC JWT tokens are issued with a trailing '",
            "            '\".\" (empty third segment) — a missing dot usually means the paste was truncated. '",
            "            'Re-copy from the Account Details tab at https://cdr.ffiec.gov/public/PWS/PublicLogin.aspx',",
            "            stacklevel=2,",
            "        )",
            "    if not t.startswith('ey'):",
            "        warnings.warn(",
            "            \"Bearer token does not start with 'ey'. FFIEC JWTs begin with the base64url header \"",
            "            \"'ey...' — this token likely isn't a JWT.\",",
            "            stacklevel=2,",
            "        )",
            "",
            "def get_credentials():",
            "    \"\"\"Blocking credential fetch: env vars -> .env -> text prompts. Returns OAuth2Credentials.\"\"\"",
            "    username, token = _resolve_env_credentials()",
            "    if not username:",
            "        username = input('FFIEC username: ').strip()",
            "    if not token:",
            "        import getpass",
            "        token = getpass.getpass('FFIEC bearer token (hidden): ').strip()",
            "    _warn_about_token_shape(token)",
            "    creds = OAuth2Credentials(username=username, bearer_token=token)",
            "    print(f'Credentials loaded. Token expires: {creds.token_expires} (expired? {creds.is_expired})')",
            "    return creds",
            "",
            "def show_credentials_form(target_name: str = 'creds'):",
            "    \"\"\"Render an ipywidgets credentials form. On Submit, sets globals()[target_name] to an OAuth2Credentials.",
            "",
            "    If ipywidgets / IPython aren't available, falls through to get_credentials() (blocking text prompts).",
            "    If env vars or .env already supply both values, skips the form entirely and returns creds directly.",
            "    \"\"\"",
            "    # Fast path: env/.env already satisfied both fields — no UI needed.",
            "    username, token = _resolve_env_credentials()",
            "    if username and token:",
            "        _warn_about_token_shape(token)",
            "        creds = OAuth2Credentials(username=username, bearer_token=token)",
            "        print(f'Credentials loaded from environment. Token expires: {creds.token_expires} (expired? {creds.is_expired})')",
            "        # Inject into caller's notebook globals so downstream cells see `creds`.",
            "        import inspect",
            "        caller_globals = inspect.stack()[1].frame.f_globals",
            "        caller_globals[target_name] = creds",
            "        return creds",
            "",
            "    # Try the widget path; fall back to text prompts if anything is missing.",
            "    try:",
            "        import ipywidgets as widgets",
            "        from IPython.display import display",
            "    except ImportError:",
            "        print('ipywidgets not available — falling back to text prompts.')",
            "        print('  (pip install ipywidgets for a nicer form-based input)')",
            "        creds = get_credentials()",
            "        import inspect",
            "        inspect.stack()[1].frame.f_globals[target_name] = creds",
            "        return creds",
            "",
            "    # Capture the caller's globals so the Submit handler can write `creds` back.",
            "    import inspect",
            "    caller_globals = inspect.stack()[1].frame.f_globals",
            "",
            "    user_field = widgets.Text(",
            "        value=username or '',",
            "        placeholder='FFIEC PWS username',",
            "        description='Username:',",
            "        layout=widgets.Layout(width='420px'),",
            "    )",
            "    token_field = widgets.Password(",
            "        value=token or '',",
            "        placeholder='JWT bearer token (starts with ey..., ends with .)',",
            "        description='Token:',",
            "        layout=widgets.Layout(width='420px'),",
            "    )",
            "    submit = widgets.Button(description='Submit', button_style='primary', icon='check')",
            "    status = widgets.Output()",
            "",
            "    def _on_submit(_):",
            "        status.clear_output()",
            "        with status:",
            "            u = (user_field.value or '').strip()",
            "            t = (token_field.value or '').strip()",
            "            if not u or not t:",
            "                print('Please fill in both fields.')",
            "                return",
            "            # Surface paste-truncation warnings visibly in the form area.",
            "            if not t.endswith('.'):",
            "                print('⚠ Warning: token does not end with \".\". FFIEC JWTs end in a literal \".\" — '",
            "                      'a missing dot usually means the paste was truncated. Re-copy if auth fails.')",
            "            if not t.startswith('ey'):",
            "                print(\"⚠ Warning: token does not start with 'ey' — likely not a JWT.\")",
            "            try:",
            "                creds = OAuth2Credentials(username=u, bearer_token=t)",
            "            except Exception as e:",
            "                print(f'Invalid credentials: {e}')",
            "                return",
            "            caller_globals[target_name] = creds",
            "            print(f'✓ Credentials set in `{target_name}`. Token expires: {creds.token_expires} (expired? {creds.is_expired}).')",
            "            print('  Proceed to the next cell.')",
            "",
            "    submit.on_click(_on_submit)",
            "    display(widgets.VBox([user_field, token_field, submit, status]))",
            "    print('Fill the form above and click Submit. `' + target_name + '` will be set in your notebook.')",
            "    return None  # Value is delivered via globals[target_name] on Submit.",
            "",
            "print('Two ways to authenticate in the next cell:')",
            "print('  creds = get_credentials()       # blocking, text prompts')",
            "print('  show_credentials_form()         # interactive ipywidgets form (sets `creds` on Submit)')",
        ),
    ]


# ---------------------------------------------------------------------------
# 01_quickstart.ipynb
# ---------------------------------------------------------------------------

quickstart = notebook([
    md(
        "# Quickstart: Your First FFIEC API Call",
        "",
        "Goal: make one API call in under 2 minutes and confirm your credentials work.",
        "",
        "**Prerequisites:**",
        "1. `pip install ffiec-data-connect` (or set `USE_LOCAL_SRC = True` in Step 0 to run against the repo's `src/` tree without installing)",
        "2. A JWT bearer token from https://cdr.ffiec.gov/public/PWS/PublicLogin.aspx (Account Details tab)",
        "3. Your username + token supplied via **any** of: the `FFIEC_USERNAME` / `FFIEC_BEARER_TOKEN` env vars, a `.env` file in this directory (needs `pip install python-dotenv`), or an interactive prompt at Step 0. Never hard-code secrets in the notebook.",
    ),
    *step_zero_cells(),
    md(
        "## Step 1: Load credentials",
        "",
        "Running the next cell renders an interactive form (username + password field + Submit button). Click Submit and `creds` will be set in your notebook namespace.",
        "",
        "- If your `FFIEC_USERNAME` / `FFIEC_BEARER_TOKEN` env vars (or a `.env` file) are already set, the form is skipped and `creds` is populated immediately.",
        "- If `ipywidgets` isn't installed, it falls back to text prompts in the cell output.",
        "- For fully scripted notebooks (no UI), use `creds = get_credentials()` instead — it blocks on text prompts only.",
    ),
    code(
        "show_credentials_form()   # Sets `creds` in this notebook when you click Submit.",
    ),
    md(
        "## Step 2: Fetch available Call Report reporting periods",
        "",
        "This is the lightest-weight endpoint — a great first call to verify your credentials.",
    ),
    code(
        "from ffiec_data_connect import collect_reporting_periods",
        "",
        "periods = collect_reporting_periods(creds, series='call')",
        "",
        "print(f'Got {len(periods)} reporting periods')",
        "print(f'Earliest: {periods[0]}')",
        "print(f'Latest:   {periods[-1]}')",
    ),
    md(
        "## Step 3: Get data for one bank",
        "",
        "We'll use the **second-to-last** reporting period — the very latest period is often a future quarter that institutions haven't filed for yet.",
    ),
    code(
        "from ffiec_data_connect import collect_data",
        "",
        "# Bank of America, N.A. — RSSD 480228",
        "# Use periods[-2] to avoid the (possibly unfiled) latest period",
        "target_period = periods[-2]",
        "print(f'Fetching data for {target_period}...')",
        "",
        "df = collect_data(",
        "    creds,",
        "    reporting_period=target_period,",
        "    rssd_id='480228',",
        "    series='call',",
        "    output_type='pandas',",
        ")",
        "",
        "print(f'Got {len(df):,} data points')",
        "df.head()",
    ),
    md(
        "## That's it!",
        "",
        "You successfully:",
        "- Authenticated with the FFIEC REST API",
        "- Listed available reporting periods",
        "- Downloaded XBRL data for one institution",
        "",
        "**Next steps:**",
        "- [`02_bulk_download_call_reports.ipynb`](02_bulk_download_call_reports.ipynb) — time series for one bank",
        "- [`03_peer_group_analysis.ipynb`](03_peer_group_analysis.ipynb) — compare multiple banks",
        "- [`04_incremental_updates.ipynb`](04_incremental_updates.ipynb) — monitor new filings",
    ),
])


# ---------------------------------------------------------------------------
# 02_bulk_download_call_reports.ipynb
# ---------------------------------------------------------------------------

bulk_download = notebook([
    md(
        "# Bulk Download: Time Series for One Bank",
        "",
        "Goal: pull Call Report XBRL data for one bank across several quarters, combine it into a single DataFrame, and plot a metric over time.",
        "",
        "**Use case:** You're tracking how a bank's total assets, loans, or deposits have evolved quarter-over-quarter.",
        "",
        "**Tip:** The library's built-in rate limiter (2500 req/hr) means you can safely pull dozens of quarters in sequence without worrying about throttling.",
    ),
    *step_zero_cells(),
    md("## Setup"),
    code(
        "import pandas as pd",
        "from ffiec_data_connect import (",
        "    collect_data,",
        "    collect_reporting_periods,",
        ")",
    ),
    md(
        "### Authenticate",
        "",
        "Running the next cell shows an interactive form unless env vars / `.env` already provide credentials. Submitting sets `creds` in the notebook namespace. For scripted use, replace with `creds = get_credentials()`.",
    ),
    code(
        "show_credentials_form()   # Sets `creds` on Submit.",
    ),
    md(
        "## Pick a bank and a date range",
        "",
        "For this example: Bank of America (RSSD 480228), last 8 quarters.",
    ),
    code(
        "RSSD_ID = '480228'  # Bank of America, N.A.",
        "NUM_QUARTERS = 8",
        "",
        "all_periods = collect_reporting_periods(creds, series='call')",
        "# Skip the latest period — it may be a future quarter not yet filed",
        "target_periods = all_periods[-(NUM_QUARTERS + 1):-1]",
        "",
        "print(f'Fetching {len(target_periods)} quarters:')",
        "for p in target_periods:",
        "    print(f'  {p}')",
    ),
    md(
        "## Fetch each quarter",
        "",
        "Each call returns the full XBRL filing. We tag each row with its reporting period so we can concatenate into a long-format DataFrame.",
    ),
    code(
        "quarterly_data = []",
        "",
        "for period in target_periods:",
        "    print(f'Fetching {period}...', end=' ')",
        "    df = collect_data(",
        "        creds,",
        "        reporting_period=period,",
        "        rssd_id=RSSD_ID,",
        "        series='call',",
        "        output_type='pandas',",
        "    )",
        "    df['reporting_period'] = period",
        "    quarterly_data.append(df)",
        "    print(f'{len(df)} items')",
        "",
        "combined = pd.concat(quarterly_data, ignore_index=True)",
        "print(f'\\nCombined: {len(combined):,} rows')",
    ),
    md(
        "## Extract one metric across time",
        "",
        "Call Report data uses MDRM codes to identify individual data points. For example:",
        "- `RCFD2170` — Total assets (consolidated)",
        "- `RCFD2200` — Total deposits",
        "- `RCFD2122` — Total loans and leases, net",
        "",
        "See the [Call Report MDRM Data Dictionary](https://cdr.ffiec.gov/public/ManageFacsimiles.aspx) for the full list.",
    ),
    code(
        "# Extract total assets over time.",
        "# RCFD = consolidated (banks with foreign offices); RCON = domestic-only. Bank of America",
        "# files RCFD. For a small community bank, swap to 'RCON2170' or accept either via .isin().",
        "MDRM_TOTAL_ASSETS_CODES = ['RCFD2170', 'RCON2170']",
        "",
        "time_series = (",
        "    combined[combined['mdrm'].isin(MDRM_TOTAL_ASSETS_CODES)]",
        "    [['reporting_period', 'int_data']]",
        "    .rename(columns={'int_data': 'total_assets_thousands'})",
        "    .sort_values('reporting_period')",
        "    .reset_index(drop=True)",
        ")",
        "",
        "if time_series.empty:",
        "    raise ValueError(",
        "        f'No rows matched {MDRM_TOTAL_ASSETS_CODES} in the combined data. '",
        "        f'Did the fetch loop succeed? Sample of available MDRMs: '",
        "        f'{combined[\"mdrm\"].value_counts().head(10).to_dict()}'",
        "    )",
        "",
        "time_series",
    ),
    md("## Plot it"),
    code(
        "import matplotlib.pyplot as plt",
        "",
        "fig, ax = plt.subplots(figsize=(10, 5))",
        "ax.plot(time_series['reporting_period'], time_series['total_assets_thousands'] / 1e6, marker='o')",
        "ax.set_title(f'Total Assets Over Time — RSSD {RSSD_ID}')",
        "ax.set_xlabel('Reporting Period')",
        "ax.set_ylabel('Total Assets ($B)')",
        "ax.grid(True, alpha=0.3)",
        "plt.xticks(rotation=45)",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "## Save for later analysis",
        "",
        "For production pipelines, save the combined DataFrame to Parquet — efficient, preserves dtypes, and fast to reload.",
    ),
    code(
        "combined.to_parquet('bank_480228_8q.parquet', index=False)",
        "print(f'Saved {len(combined):,} rows')",
    ),
    md(
        "## Optional: archive a PDF snapshot per quarter",
        "",
        "For audit trails or regulator-facing workflows, it's often useful to keep an",
        "auditor-readable PDF copy of each quarterly Call Report alongside the structured",
        "data. As of 3.0.0rc4, `collect_data` accepts `output_type='pdf'` on Call Report",
        "series to return raw PDF bytes directly from the FFIEC server — no rendering",
        "needed, no extra dependencies.",
        "",
        "This cell is optional — it makes `NUM_QUARTERS` extra API calls (one per",
        "quarter). Skip it if you don't need an archive.",
    ),
    code(
        "from pathlib import Path",
        "",
        "pdf_dir = Path('call_report_pdfs')",
        "pdf_dir.mkdir(exist_ok=True)",
        "",
        "for period in target_periods:",
        "    print(f'Fetching PDF for {period}...', end=' ')",
        "    pdf_bytes = collect_data(",
        "        creds,",
        "        reporting_period=period,",
        "        rssd_id=RSSD_ID,",
        "        series='call',",
        "        output_type='pdf',",
        "    )",
        "    filename = f'rssd{RSSD_ID}_{period.replace(\"/\", \"-\")}.pdf'",
        "    (pdf_dir / filename).write_bytes(pdf_bytes)",
        "    print(f'{len(pdf_bytes):,} bytes -> {filename}')",
        "",
        "print(f'\\nSaved {len(target_periods)} PDFs under {pdf_dir}/')",
    ),
])


# ---------------------------------------------------------------------------
# 03_peer_group_analysis.ipynb
# ---------------------------------------------------------------------------

peer_group = notebook([
    md(
        "# Peer Group Analysis",
        "",
        "Goal: identify a peer group of banks (e.g., all banks in a single state) and pull comparable metrics across the group for one reporting period.",
        "",
        "**Use case:** Comparing your institution's ratios against peers, benchmarking, regulatory analysis.",
    ),
    *step_zero_cells(),
    md("## Setup"),
    code(
        "import pandas as pd",
        "from ffiec_data_connect import (",
        "    collect_data,",
        "    collect_filers_on_reporting_period,",
        "    collect_reporting_periods,",
        ")",
    ),
    md(
        "### Authenticate",
        "",
        "Running the next cell shows an interactive form unless env vars / `.env` already provide credentials. Submitting sets `creds` in the notebook namespace. For scripted use, replace with `creds = get_credentials()`.",
    ),
    code(
        "show_credentials_form()   # Sets `creds` on Submit.",
    ),
    md("## Step 1: Get the panel of reporters for a period"),
    code(
        "periods = collect_reporting_periods(creds, series='call')",
        "# Use second-to-last period — latest may be a future quarter not yet filed",
        "latest = periods[-2]",
        "print(f'Using reporting period: {latest}')",
        "",
        "panel = collect_filers_on_reporting_period(",
        "    creds,",
        "    reporting_period=latest,",
        "    output_type='pandas',",
        ")",
        "",
        "print(f'Panel has {len(panel):,} institutions')",
        "panel.head()",
    ),
    md(
        "## Step 2: Filter to your peer group",
        "",
        "We default to Rhode Island because it's small (~15 banks) — the loop finishes in under a minute. If you pick a very small state *and* every bank in it is a small community bank, some MDRM codes may not appear in the panel. The pivot step later will warn you, and Step 5 will skip any ratio whose inputs are missing. For a denser panel, try `'CA'`, `'NY'`, or `'TX'`.",
    ),
    code(
        "# Example: all banks in Rhode Island",
        "TARGET_STATE = 'RI'",
        "",
        "peers = panel[panel['state'] == TARGET_STATE].copy()",
        "print(f'Found {len(peers)} banks in {TARGET_STATE}')",
        "peers[['rssd', 'name', 'city', 'state']].head(10)",
    ),
    md(
        "## Step 3: Pull Call Report data for each peer",
        "",
        "This makes N API calls — one per peer. With the built-in rate limiter (2500 req/hr), you can comfortably handle a few hundred peers. For larger groups, consider running overnight or splitting the work.",
    ),
    code(
        "peer_data = []",
        "failed = []   # Track failures so we don't silently lose banks.",
        "",
        "for idx, row in peers.iterrows():",
        "    rssd = row['rssd']",
        "    name = row['name']",
        "    print(f'[{idx+1}/{len(peers)}] {rssd} — {name[:50]}', end=' ')",
        "    try:",
        "        df = collect_data(",
        "            creds,",
        "            reporting_period=latest,",
        "            rssd_id=rssd,",
        "            series='call',",
        "            output_type='pandas',",
        "        )",
        "        df['rssd'] = rssd",
        "        df['name'] = name",
        "        peer_data.append(df)",
        "        print(f'OK ({len(df)} items)')",
        "    except Exception as e:",
        "        # Print the full message — a bare type name hides rate limits, missing filings, etc.",
        "        failed.append({'rssd': rssd, 'name': name, 'error': f'{type(e).__name__}: {e}'})",
        "        print(f'FAIL: {type(e).__name__}: {e}')",
        "",
        "if not peer_data:",
        "    raise RuntimeError(",
        "        f'No banks fetched successfully ({len(failed)} failures). '",
        "        f'Check credentials, rate limits, and the first few entries in `failed`.'",
        "    )",
        "",
        "all_peer_data = pd.concat(peer_data, ignore_index=True)",
        "print(f'\\nFetched {len(peer_data)} banks, {len(failed)} failed, {len(all_peer_data):,} total rows')",
        "if failed:",
        "    print(f'First few failures: {failed[:3]}')",
    ),
    md(
        "## Step 4: Extract comparable metrics",
        "",
        "Pivot the long-format data into a wide comparison table. Each row is a bank, each column is a metric.",
    ),
    code(
        "# Common Call Report MDRM codes.",
        "# Banks with foreign offices file RCFD (consolidated); banks without file RCON (domestic-only).",
        "# Include both so we work for community banks AND multinationals. aggfunc='first' coalesces",
        "# because a given bank files exactly one of the pair for each metric.",
        "METRICS = {",
        "    'RCFD2170': 'total_assets',     'RCON2170': 'total_assets',",
        "    'RCFD2200': 'total_deposits',   'RCON2200': 'total_deposits',",
        "    'RCFD2122': 'net_loans_leases', 'RCON2122': 'net_loans_leases',",
        "    'RCFD3210': 'total_equity',     'RCON3210': 'total_equity',",
        "}",
        "",
        "subset = all_peer_data[all_peer_data['mdrm'].isin(METRICS.keys())].copy()",
        "subset['metric'] = subset['mdrm'].map(METRICS)",
        "",
        "if subset.empty:",
        "    raise ValueError(",
        "        'No rows matched any of the expected MDRM codes. '",
        "        'Check that `all_peer_data[\"mdrm\"]` contains RCFD/RCON values.'",
        "    )",
        "",
        "comparison = (",
        "    subset.pivot_table(",
        "        index=['rssd', 'name'],",
        "        columns='metric',",
        "        values='int_data',",
        "        aggfunc='first',",
        "    )",
        "    .reset_index()",
        ")",
        "",
        "# Warn if any expected metric is missing across the whole panel — Step 5 will crash otherwise.",
        "expected_metrics = set(METRICS.values())",
        "missing_metrics = expected_metrics - set(comparison.columns)",
        "if missing_metrics:",
        "    print(f'WARNING: no bank in the panel reported these metrics: {sorted(missing_metrics)}')",
        "    print('Step 5 will skip ratios that depend on them.')",
        "",
        "if 'total_assets' in comparison.columns:",
        "    comparison = comparison.sort_values('total_assets', ascending=False)",
        "",
        "# Convert from thousands to millions for readability.",
        "for col in expected_metrics:",
        "    if col in comparison.columns:",
        "        comparison[col] = comparison[col] / 1_000",
        "",
        "comparison.head(10)",
    ),
    md("## Step 5: Compute derived ratios"),
    code(
        "# Compute each ratio only if both inputs are present. Guards against sparse panels",
        "# where small banks may not have filed every MDRM we expected.",
        "display_cols = ['name']",
        "",
        "if {'net_loans_leases', 'total_deposits'}.issubset(comparison.columns):",
        "    comparison['loans_to_deposits'] = (",
        "        comparison['net_loans_leases'] / comparison['total_deposits']",
        "    )",
        "    display_cols.append('loans_to_deposits')",
        "else:",
        "    print('Skipping loans_to_deposits — missing net_loans_leases or total_deposits')",
        "",
        "if {'total_equity', 'total_assets'}.issubset(comparison.columns):",
        "    comparison['equity_to_assets'] = (",
        "        comparison['total_equity'] / comparison['total_assets']",
        "    )",
        "    display_cols.append('equity_to_assets')",
        "else:",
        "    print('Skipping equity_to_assets — missing total_equity or total_assets')",
        "",
        "if 'total_assets' in comparison.columns:",
        "    display_cols.insert(1, 'total_assets')",
        "",
        "comparison[display_cols].head(10)",
    ),
    md(
        "## Tips for larger peer groups",
        "",
        "- **Hundreds of banks**: use `AsyncCompatibleClient` for parallel fetches (see the REST demo notebook)",
        "- **Thousands of banks**: split the work into batches, checkpoint to disk, handle failures gracefully",
        "- **State subsets**: the `panel` DataFrame has `state`, `city`, `fdic_cert_number`, and more — filter however you need",
    ),
])


# ---------------------------------------------------------------------------
# 04_incremental_updates.ipynb
# ---------------------------------------------------------------------------

incremental = notebook([
    md(
        "# Incremental Updates: Monitor New Filings",
        "",
        "Goal: for an ETL or monitoring workflow, find banks that have filed (or amended their filing) since your last check.",
        "",
        "**Use case:**",
        "- Nightly cron job that pulls only new/amended filings",
        "- Regulatory dashboard that refreshes as institutions file",
        "- Audit trail of filing timestamps",
        "",
        "The FFIEC REST API exposes two endpoints that support this pattern:",
        "- `collect_filers_since_date` — just the RSSD IDs that filed after a given date",
        "- `collect_filers_submission_date_time` — RSSD IDs **plus** the exact submission timestamp",
    ),
    *step_zero_cells(),
    md("## Setup"),
    code(
        "from datetime import datetime, timedelta",
        "import pandas as pd",
        "from ffiec_data_connect import (",
        "    collect_data,",
        "    collect_filers_since_date,",
        "    collect_filers_submission_date_time,",
        ")",
    ),
    md(
        "### Authenticate",
        "",
        "Running the next cell shows an interactive form unless env vars / `.env` already provide credentials. Submitting sets `creds` in the notebook namespace. For scripted use, replace with `creds = get_credentials()`.",
    ),
    code(
        "show_credentials_form()   # Sets `creds` on Submit.",
    ),
    md(
        "## Pattern 1: Which RSSD IDs filed since last run?",
        "",
        "In a real ETL job, you'd persist `last_run_date` to a database or file between runs. Here we'll simulate it as 30 days ago.",
    ),
    code(
        "# Your current reporting period (the quarter you're pulling)",
        "REPORTING_PERIOD = '12/31/2024'",
        "",
        "# Last time your ETL ran",
        "last_run = (datetime.now() - timedelta(days=30)).strftime('%m/%d/%Y')",
        "print(f'Looking for filings since: {last_run}')",
        "",
        "new_filers = collect_filers_since_date(",
        "    creds,",
        "    reporting_period=REPORTING_PERIOD,",
        "    since_date=last_run,",
        ")",
        "",
        "print(f'{len(new_filers)} institutions filed since {last_run}')",
        "print(f'First 5: {new_filers[:5]}')",
    ),
    md(
        "## Pattern 2: Get the submission timestamps",
        "",
        "When you need to know **exactly when** each institution filed (for SLA monitoring, audit trails, or ordering by recency).",
    ),
    code(
        "submissions = collect_filers_submission_date_time(",
        "    creds,",
        "    since_date=last_run,",
        "    reporting_period=REPORTING_PERIOD,",
        "    output_type='pandas',",
        "    # As of 3.0.0rc6 the library converts the submission timestamp",
        "    # into a tz-aware datetime (America/New_York — FFIEC's wall-clock",
        "    # zone, DST handled by zoneinfo). Before rc6 the parameter was a",
        "    # silent no-op and you had to pd.to_datetime() the strings yourself.",
        "    date_output_format='python_format',",
        ")",
        "",
        "print(f'Got {len(submissions)} submissions')",
        "submissions.head()",
    ),
    md(
        "## Find the most recent filers",
        "",
        "Because `datetime` is already a tz-aware pandas column (`datetime64[ns, America/New_York]`), sorting and comparisons work directly — no `pd.to_datetime` dance.",
    ),
    code(
        "# Sort by submission time, newest first. The column is already a",
        "# tz-aware datetime, so `.sort_values` / comparisons work directly.",
        "recent = submissions.sort_values('datetime', ascending=False).head(20)",
        "",
        "print('Most recent filings:')",
        "recent[['rssd', 'datetime']]",
    ),
    md(
        "## ETL pattern: fetch data only for new filers",
        "",
        "Instead of re-downloading every bank's XBRL every night, only pull the ones that filed or amended since your last run.",
    ),
    code(
        "# Simulated ETL loop — in production you'd persist results to a database",
        "updated_records = []",
        "failed = []   # Track failures: in production, feed these into your dead-letter queue / alerting.",
        "",
        "# Take first 5 for the example; in production you'd iterate all new_filers",
        "for rssd in new_filers[:5]:",
        "    print(f'Fetching {rssd}...', end=' ')",
        "    try:",
        "        df = collect_data(",
        "            creds,",
        "            reporting_period=REPORTING_PERIOD,",
        "            rssd_id=rssd,",
        "            series='call',",
        "            output_type='pandas',",
        "        )",
        "        df['rssd'] = rssd",
        "        updated_records.append(df)",
        "        print(f'OK ({len(df)} items)')",
        "    except Exception as e:",
        "        # Keep both the type name AND the message — a bare type hides rate limits, auth issues, etc.",
        "        failed.append({'rssd': rssd, 'error': f'{type(e).__name__}: {e}'})",
        "        print(f'FAIL: {type(e).__name__}: {e}')",
        "",
        "updated = pd.concat(updated_records, ignore_index=True) if updated_records else pd.DataFrame()",
        "print(f'\\nUpdated {len(updated_records)} institutions, {len(failed)} failed, {len(updated):,} total data points')",
        "if failed:",
        "    print(f'Failures: {failed}')",
    ),
    md(
        "## Production checklist",
        "",
        "For a real scheduled job:",
        "",
        "1. **Persist `last_run_date`** — store it in your database or a small state file",
        "2. **Handle failures** — if one bank errors, don't fail the whole run (wrap in try/except, log failures)",
        "3. **Idempotency** — upsert by `(rssd, reporting_period, mdrm)` so re-runs are safe",
        "4. **Token rotation** — JWT tokens expire every 90 days; `creds.is_expired` is your friend",
        "5. **Rate limiting** — built-in limiter handles the 2500/hr cap, but for very large panels consider async + batching",
        "6. **Monitoring** — log counts of fetched banks, record durations, alert on anomalies",
    ),
])


# ---------------------------------------------------------------------------
# Write all notebooks
# ---------------------------------------------------------------------------

NOTEBOOKS = {
    "01_quickstart.ipynb": quickstart,
    "02_bulk_download_call_reports.ipynb": bulk_download,
    "03_peer_group_analysis.ipynb": peer_group,
    "04_incremental_updates.ipynb": incremental,
}


def main() -> None:
    out_dir = Path(__file__).parent
    for name, nb in NOTEBOOKS.items():
        path = out_dir / name
        with open(path, "w") as f:
            json.dump(nb, f, indent=1)
            f.write("\n")
        print(f"Wrote {path.relative_to(Path.cwd())} ({len(nb['cells'])} cells)")


if __name__ == "__main__":
    main()
