name: Dependency Review & Security

on:
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Mondays at 6 AM UTC

# Cancel in-progress runs for the same branch
concurrency:
  group: deps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Dependency Review
      uses: actions/dependency-review-action@v4.3.2
      with:
        fail-on-severity: moderate
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, MPL-2.0
        comment-summary-in-pr: always

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'

    - name: Install pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit

    - name: Run security audit
      run: |
        echo "::group::Security audit of dependencies"
        pip-audit --format=json --output=security-audit.json . || echo "Vulnerabilities found"
        pip-audit .
        echo "::endgroup::"

    - name: Upload security audit results
      if: always()
      uses: actions/upload-artifact@v4.3.3
      with:
        name: security-audit-results
        path: security-audit.json
        retention-days: 30
