name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: 
      name: pypi
      url: https://pypi.org/p/ffiec-data-connect
    permissions:
      id-token: write  # Required for trusted publishing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Verify package
      run: |
        python -m twine check dist/*
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      
  verify-install:
    name: Verify Installation
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install from PyPI
      run: |
        python -m pip install --upgrade pip
        # Wait a few minutes for package to be available
        sleep 180
        pip install ffiec-data-connect
        
    - name: Test basic import
      run: |
        python -c "
        import ffiec_data_connect
        print(f'Successfully installed ffiec-data-connect v{ffiec_data_connect.__version__}')
        from ffiec_data_connect import WebserviceCredentials
        print('✅ Basic import test passed')
        "